[agent]
name = "robloxCatalogAgent"
version = "0.0.1"
description = "Agent that can search and retrieve items from the Roblox Catalog API for outfit creation"

[options.MODEL_API_KEY]
type = "string"
description = "API key for the model provider"

[options.MODEL_NAME]
type = "string"
description = "What model to use (e.g 'gpt-4o')"
default = "gpt-4o"

[options.MODEL_PROVIDER]
type = "string"
description = "What model provider to use (e.g 'openai')"
default = "openai"

[options.MODEL_TEMPERATURE]
type = "string"
description = "Temperature for the model (0.0 to 1.0)"
default = "0.1"

[options.MODEL_MAX_TOKENS]
type = "string"
description = "Maximum tokens for the model response"
default = "8000"

[options.MODEL_BASE_URL]
type = "string"
description = "Base URL for the model API (optional)"
default = ""

[options.CORAL_CONNECTION_URL]
type = "string"
description = "URL to connect to the Coral server"

[options.CORAL_AGENT_ID]
type = "string"
description = "Agent ID for Coral server communication"

[runtimes.executable]
command = ["bash", "-c", "./run_agent.sh main.py"]