[agent]
name = "robloxCatalogAgent"
version = "1.0.1"
description = "Specialist agent for searching and retrieving Roblox catalog items including clothing, accessories, faces, and more"

[options.OPENAI_API_KEY]
type = "string"
description = "The OpenAI API key to use for AI processing"

[options.MODEL_NAME]
type = "string"
description = "What model to use (e.g 'gpt-4o-mini')"
default = "gpt-4o-mini"

[options.MODEL_PROVIDER]
type = "string"
description = "What model provider to use (e.g 'openai', etc)"
default = "openai"

[options.MODEL_MAX_TOKENS]
type = "string"
description = "Max tokens to use"
default = "16000"

[options.MODEL_TEMPERATURE]
type = "string"
description = "What model temperature to use"
default = "0.1"

[options.TIMEOUT_MS]
type = "string"
description = "Connection/tool timeouts in ms"
default = "60000"

[options.CORAL_SERVER_URL]
type = "string"
description = "URL of the Coral Protocol server"
default = "http://localhost:5556"

[runtimes.executable]
command = ["bash", "-c", "./run_agent.sh main.py"]

[runtimes.docker]
image = "rushabhrunwal/roblox-catalog-agent:v1.0.1"