[[local-agent]]
path = "agents/interface"

[[local-agent]]
path = "agents/robloxCatalogAgent"

# Export configuration for the Docker runtime of the Roblox Catalog Agent
[local-agent.export.docker]
quantity = 10
pricing = { min_price = { type = "usd", amount = 0.01 }, max_price = { type = "usd", amount = 5.0 } }